[package]
name = "youtube"
version = "1.0.0"
authors = ["Jaemin Hong <hjm0901@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
clap = { version = "=4.4.2", features = ["derive"] }
chrono = "0.4.38"
